### ISSUE TITLE
Creation of WebSocket tunnel to guacd failed: Connection timed out.

### ISSUE THREAD

**Issue by MeriemBo** [jamhall/guacamole-test-server#3]
Hello , I'm trying to use this server for test purposes, I got my frontend up and running , with the following configuration : 

      this.manager = new RemoteDesktopManager(tunnel)

        const parameters = {
            ip: '52.139.24.171',
            port: 3389,
            type: 'rdp',
            image: 'image/png',
            width: window.screen.width,
            height: window.screen.height,
            username: 'TestSavvyAdmin',
            password: 'TestSavvyAdmin!4',
            dpi :96

        };
        {address}&image=image/png&audio=audio/L16&dpi=96&width=n&height=n
    
        this.manager.connect(parameters);

I also have my server running , but when I run the jar , I can have a connection to guacd and I get the following erroe : 

    C:\guacamole-test-server>java -jar target/gts.jar --guacd-host 1.2.3.4 --guacd-port 4822 --port 8080

    2019-06-25 12:20:10,389 [INFO] org.eclipse.jetty.util.log - Logging initialized @200ms to 
    org.eclipse.jetty.util.log.Slf4jLog
    2019-06-25 12:20:10,507 [INFO] org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT, build 
    timestamp: 2017-11-21T16:27:37-05:00, git hash: 82b8fb23f757335bb3329d540ce37a2a26
    15f0a8
    2019-06-25 12:20:10,541 [INFO] org.eclipse.jetty.server.session - DefaultSessionIdManager 
    workerName=node0
    2019-06-25 12:20:10,544 [INFO] org.eclipse.jetty.server.session - No SessionScavenger set, using 
    defaults
    2019-06-25 12:20:10,546 [INFO] org.eclipse.jetty.server.session - Scavenging every 600000ms
    2019-06-25 12:20:10,718 [INFO] eu.jamiehall.gts.ws.WebSocketTunnelModule - Loading Jetty 9 
    WebSocket support...
     2019-06-25 12:20:10,804 [INFO] org.eclipse.jetty.server.handler.ContextHandler - Started 
     o.e.j.s.ServletContextHandler@229f66ed{/,null,AVAILABLE}
     2019-06-25 12:20:11,106 [INFO] org.eclipse.jetty.server.AbstractConnector - Started 
     ServerConnector@2a5c8d3f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
     2019-06-25 12:20:11,106 [INFO] org.eclipse.jetty.server.Server - Started @924ms
     2019-06-25 12:20:19,119 [DEBUG] org.apache.guacamole.net.InetGuacamoleSocket - Connecting to 
     guacd at 1.2.3.4:4822.
     2019-06-25 12:20:34,120 [ERROR] eu.jamiehall.gts.ws.WebSocketTunnelServlet - Creation of 
      WebSocket tunnel to guacd failed: Connection timed out.
       2019-06-25 12:20:34,121 [DEBUG] eu.jamiehall.gts.ws.WebSocketTunnelServlet - Error connecting 
       WebSocket tunnel.
       org.apache.guacamole.GuacamoleUpstreamTimeoutException: Connection timed out.
        at org.apache.guacamole.net.InetGuacamoleSocket.<init>(InetGuacamoleSocket.java:111)
        at eu.jamiehall.gts.tunnel.TunnelRequestService.createTunnel(TunnelRequestService.java:114)
        at eu.jamiehall.gts.ws.WebSocketTunnelListener.createTunnel(WebSocketTunnelListener.java:60)
        

any ideas about what I'm doing wrong ? thank you

**Comment by shakscode** [comment]
any solution found??

**Comment by SimpleHomelab** [comment]
I am facing the same issue. Please share any solution.

**Comment by shaksthesailor** [comment]
ensure you have all the dependency installed....wsock alone not needed.....

**Comment by sean-custer** [comment]
Any solutions found yet?

**Comment by rghv932** [comment]
Any solution found by anyone?

**Comment by coda1024** [comment]
.

**Comment by nasri-mohamed** [comment]
any solution ?
